### ISSUE TITLE
KeyError: 'args.model' 

### ISSUE THREAD

**Issue by AlonDan** [sczhou/LEDNet#5]
I followed the step-by-step installation, and did everything needed including installing pytorch and downloaded the pre-trained model.

As I'm trying the very first test:
```
# test LEDNet (paper model)
python inference_lednet.py --model lednet --test_path ./inputs
```

I get this error:
```
python inference_lednet.py --model lednet --test_path ./inputs
Traceback (most recent call last):
  File "inference_lednet.py", line 54, in <module>
    ckpt_path = load_file_from_url(url=pretrain_model_url['args.model'],
KeyError: 'args.model'
```
---

Maybe I missed something in the installation?
Can you please explain how do I fix that?
Thanks ahead! 🙏

**Comment by sczhou** [comment]
Fixed it.

**Comment by AlonDan** [comment]
> Fixed it.

I've downloaded the latest version and tried again, this time I get these errors:

`Traceback (most recent call last):
  File "basicsr/train.py", line 225, in <module>
    train_pipeline(root_path)
  File "basicsr/train.py", line 135, in train_pipeline
    result = create_train_val_dataloader(opt, logger)
  File "basicsr/train.py", line 77, in create_train_val_dataloader
    train_set = build_dataset(dataset_opt)
  File "z:\lednet\basicsr\data\__init__.py", line 34, in build_dataset
    dataset = DATASET_REGISTRY.get(dataset_opt['type'])(dataset_opt)
  File "z:\lednet\basicsr\data\paired_image_dataset.py", line 54, in __init__
    self.paths = paired_paths_from_folder([self.lq_folder, self.gt_folder], ['lq', 'gt'], self.filename_tmpl)
  File "z:\lednet\basicsr\data\data_util.py", line 211, in paired_paths_from_folder
    input_paths = sorted(list(scandir(input_folder, recursive=True, full_path=True)))
  File "z:\lednet\basicsr\utils\misc.py", line 73, in _scandir
    for entry in os.scandir(dir_path):
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/mnt/lustre/sczhou/datasets/deblurring/LOLBlur/train/low_blur_noise'`

Am I doing something wrong? or needs another fix maybe?
Thanks ahead!
